name: Tag, Build, and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Automatic Tagging
      id: tag_version
      uses: anothrNick/github-tag-action@v1.40.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: "v"
        default_bump: "minor"
        release_branches: main

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: thecodingsheikh/deepeval-api:${{ steps.tag_version.outputs.new_tag }}
